development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:fd53465d1d41c6bdd4a5da166eb78180@cod.redistogo.com:11102/
  channel_prefix: Fullstack_Project_production
